extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended
  - plugin:prettier/recommended
parser: babel-eslint
plugins:
  - jest
  - import
env:
  jest/globals: false
  shared-node-browser: true
  es6: true
parserOptions:
  sourceType: module
globals:
  WebAssembly: readonly
rules:
  quote-props:
    - error
    - as-needed
    - unnecessary: true
      numbers: true
      keywords: true
overrides:
  - files:
      - '**/__tests__/**/*.js'
      - '**/?(*.)+(spec|test).js'
      - '**/__mocks__/**/*.js'
    rules:
      no-unused-expressions: 0
    env:
      jest/globals: true
