extends:
  - eslint:recommended
  - plugin:eslint-comments/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended
  - plugin:prettier/recommended
parser: babel-eslint
plugins:
  - eslint-comments
  - jest
  - import
env:
  jest/globals: false
  shared-node-browser: true
  es6: true
parserOptions:
  sourceType: module
globals:
  WebAssembly: readonly
  TextEncoder: readonly
  TextDecoder: readonly
rules:
  quote-props:
    - error
    - as-needed
    - unnecessary: true
      numbers: true
      keywords: true
  jest/consistent-test-it:
    - error
    - fn: test
      withinDescribe: it
overrides:
  - files:
      - '**/__tests__/**/*.js?(x)'
      - '**/?(*.)+(spec|test).js?(x)'
    rules:
      no-unused-expressions: 0
    env:
      jest/globals: true
