version: 2
jobs:

  build-cpp:
    docker:
      - image: mikeheddes/dcgp.js-dependencies
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Installing NPM
          command: |
            apt-get -y update
            apt-get -y -qq install npm

      - restore_cache:
          name: Restoring NPM packages from cache
          keys:
          - v1-npm-{{ checksum "package.json" }}
          - v1-npm-

      - run:
          name: Install packages
          command: npm install

      - save_cache:
          name: Saving NPM packages to cache
          paths:
            - node_modules
          key: v1-npm-{{ checksum "package.json" }}

      - run:
          name: Building artifacts
          command: npm run build:cpp

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dcgp.*

  build-js:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - restore_cache:
          name: Restoring NPM packages from cache
          keys:
          - v1-npm-{{ checksum "package.json" }}
          - v1-npm-

      - run:
          name: Install packages
          command: npm install

      - save_cache:
          name: Saving NPM packages to cache
          paths:
            - node_modules
          key: v1-npm-{{ checksum "package.json" }}

      - run:
          name: Building artifacts
          command: npm run build:js

      - run:
          name: Store package version
          command: echo "v$(cat package.json | jq -r .version)" > .circleci/dcgp-version

      - store_artifacts:
          path: lib

      - persist_to_workspace:
          root: ~/repo
          paths:
            - lib
            - .circleci/dcgp-version

  checks:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - restore_cache:
          name: Restoring NPM packages from cache
          keys:
          - v1-npm-{{ checksum "package.json" }}
          - v1-npm-

      - run:
          name: Install packages
          command: npm install

      - save_cache:
          name: Saving NPM packages to cache
          paths:
            - node_modules
          key: v1-npm-{{ checksum "package.json" }}

      - run:
          name: Linting code
          command: npm run lint

      - run:
          name: Testing code
          command: npm run test:ci

  publish-npm-package:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticating with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publishing package on NPM
          command: npm publish

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Publishing Release on GitHub
          command: |
            VERSION=$(cat .circleci/dcgp-version)
            ghr -t ${GITHUB_TOKEN} \
            -u ${CIRCLE_PROJECT_USERNAME} \
            -r ${CIRCLE_PROJECT_REPONAME} \
            -c ${CIRCLE_SHA1} \
            -delete \
            ${VERSION} ./lib/dcgp.wasm


workflows:
  version: 2
  # The main workflow tests PR's and deploys master
  main:
    jobs:
      - build-cpp
      - build-js:
          requires:
            - build-cpp
      - checks:
          requires:
            - build-js
      - publish-npm-package:
          requires:
            - build-js
            - checks
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - build-js
            - checks
          filters:
            branches:
              only: master
