version: 2
jobs:

  Install-and-Build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Pulling submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: Store emsdk commit hash
          command: |
            cd emsdk
            git rev-parse HEAD > ../.circleci/emsdk.hash

      - restore_cache:
          name: Restoring emsdk install from cache
          keys:
          - v1-emsdk-{{ checksum ".circleci/emsdk.hash" }}
          - v1-emsdk-

      - restore_cache:
          name: Restoring NPM packages from cache
          keys:
          - v1-npm-{{ checksum "package.json" }}
          - v1-npm-

      - run:
          name: Install Emscripten
          command: emsdk/emsdk install latest

      - run:
          name: Install packages
          command: npm install

      - save_cache:
          name: Saving emsdk install to cache
          paths:
            - emsdk/clang
            - emsdk/emscripten
            - emsdk/node
          key: v1-emsdk-{{ checksum ".circleci/emsdk.hash" }}

      - save_cache:
          name: Saving NPM packages to cache
          paths:
            - node_modules
          key: v1-npm-{{ checksum "package.json" }}

      - run:
          name: Activate Emscripten
          command: emsdk/emsdk activate latest

      - run:
          name: Building artifacts
          command: |
            source emsdk/emsdk_env.sh
            npm run build:cpp
            npm run build:js

      - store_artifacts:
          path: lib

      - persist_to_workspace:
          root: ~/repo
          paths:
            - lib
            - dcgp.*
            - node_modules

  Checks:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: Linting code
          command: npm run lint

      - run:
          name: Testing code
          command: npm run test:ci

  Deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticating with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publishing package
          command: npm publish

      - run:
          name: Pushing tag to GitHub
          command: |
            git tag v$(npm view dcgp version)
            git push origin --tags


workflows:
  version: 2
  # The main workflow tests PR's and deploys master
  main:
    jobs:
      - Install-and-Build
      - Checks:
          requires:
            - Install-and-Build
      - Deploy:
          requires:
            - Install-and-Build
            - Checks
          filters:
            branches:
              only: master
